### ISSUE TITLE
Add continuous integration for Linux

### ISSUE THREAD

**Issue by cagdasgerede** [dasher-project/dasher#124]

**Comment by cagdasgerede** [comment]
Enes will work on this:

You can use travisCI for this.

Check this for an example: https://github.com/Microsoft/vscode

![image](https://user-images.githubusercontent.com/12052/37269798-352b8ca8-25dd-11e8-829b-791e5834b22f.png)

**Comment by mortheria** [comment]
Yes, I will work on this.

**Comment by cagdasgerede** [comment]
This is done.
