### ISSUE TITLE
As a developer I want to investigate where and why Linux build references README file so that we can remove README file and use the richer looking README.md markdown file

### ISSUE THREAD

**Issue by cagdasgerede** [dasher-project/dasher#141]
As seen in the following TravisCI build for Linux:
https://travis-ci.org/dasher-project/dasher/builds/354900697

it errors out with 
```
config.status: error: cannot find input file: `Makefile.in'
```

Suspicion is that README file is referenced from Makefile generated from ./autogen.sh ve ./configure, and we remove it, the build process does not succeed.

We need to investigate it and find where the file is referenced.
Then we need to see if we should update the README reference to README.md or delete the dependency altogether (not sure why the build process would need to reference the README file)

**Comment by prlw1** [comment]
Are you starting from a tar file or from a git checkout? If from a tar file, Makefile.in should be there, otherwise it is an incomplete tar file. If from a git checkout, running automake creates it from Makefile.am.

**Comment by cagdasgerede** [comment]
@prlw1 

Does the following change make sense? @mortheria says that it fixes the issue in Travisci (in other words the build process does not require the existence of a README file).

https://github.com/dasher-project/dasher/pull/143

I am not an expert on autotools.

**Comment by prlw1** [comment]
On Sun, Mar 18, 2018 at 07:49:42PM +0000, Cagdas Evren Gerede wrote:
> Does the following change make sense? @mortheria says that it fixes the issue in Travisci (in other words the build process does not require the existence of a README file).
> 
> https://github.com/dasher-project/dasher/pull/143
> 
> I am not an expert on autotools.

Seems you are - using [foreign] is absolutely correct.

**Comment by prlw1** [comment]
On Sun, Mar 18, 2018 at 07:49:42PM +0000, Cagdas Evren Gerede wrote:
> @prlw1 
> 
> Does the following change make sense? @mortheria says that it fixes the issue in Travisci (in other words the build process does not require the existence of a README file).
> 
> https://github.com/dasher-project/dasher/pull/143
> 
> I am not an expert on autotools.

Oh - just looked at the patch - you want "foreign" instead of "gnu", not
instead of everything!

**Comment by mortheria** [comment]
@prlw1 
Thank you for warning, I've updated my changes.

**Comment by cagdasgerede** [comment]
https://github.com/dasher-project/dasher/pull/143
