### ISSUE TITLE
Question. Is it possible to get Releases built in the CI workflow for Android & Java?

### ISSUE THREAD

**Issue by willwade** [dasher-project/dasher#147]
I'm not that familiar with the Android & Java builds - I'm really focusing on the website integration here so bear with my ignorance!  Is it possible to get the compiled versions exported to the releases of the GitHub repo (or is that a bad idea??!)

**Comment by cagdasgerede** [comment]
Yes it is absolutely possible.

On the other hand, we still need to some investigation on what functional state they are in (whether they work or they are broken). After that we can certainly set that up.

We also need to figure out what to do with Android version. That is hosted in another repository. I am not sure if it is actively maintained. If not we can pull that repo into dasher-project organization and then include it in the overall improvements.
