### ISSUE TITLE
Win32 Wrong mouse  cursor in dasher canvas. 

### ISSUE THREAD

**Issue by ipomoena** [dasher-project/dasher#81]
It is supposed to be IDC_CROSS, but on most computers it is only tiny dot. Not very useful.

**Comment by cagdasgerede** [comment]
Tuba will work on this.

**Comment by tubanury** [comment]
I tested dasher 5.0 beta version on some computers -win7, win10- but i did not get this bug.  I will appreciate if you give more details about the issue.

**Comment by cagdasgerede** [comment]
@tubanury 
If you cannot reproduce the issue, we can close it.

Then you can work on another issue from the issue list. Can you for example write a developer guide for windows developers describing how to set up the environment, build the code and run it?

**Comment by tubanury** [comment]
Ok you may close it. But if it is not a problem for you, could you please clarify the issue that you said?
